### ISSUE TITLE
Make writing back to package.json optional

### ISSUE THREAD

**Issue by sschuberth** [spatie/npm-install-peers#12] opened 2017-07-07 12:42 UTC
I was very surprised to see `npm-install-peers` modifying my files (`package.json` and `npm-shrinkwrap.json`) and leaving my Git working tree in a dirty state. Could the implementation of #4 be changed to allow *not* to modify any files?

**Comment by sebastiandedeyne** [comment] 2017-08-16 09:10
Duplicate of #13

**Closed as completed by sebastiandedeyne** 2017-08-16 09:10 UTC
